name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev
          
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Test Lx
        run: zig build -freference-trace test

      - name: Compile Lx
        run: zig build -freference-trace check
